server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: admin_route
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: billing_route
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
        - id: delivery_route
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: notification_route
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
